name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Instalar dependências
      - name: Install dependencies
        run: npm ci

      # Build do código TypeScript
      - name: Build TypeScript
        run: npx tsc

      # Empacotar arquivos para deploy
      - name: Package Lambda
        run: zip -r lambda.zip dist/

      # Deploy para AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name discordNotification \
            --zip-file fileb://lambda.zip
